# Generated by Django 4.1.5 on 2023-08-27 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newpost",
            name="following",
            field=models.BooleanField(default=False),
        ),
    ]
