# Generated by Django 4.1.5 on 2023-09-27 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinect", "0003_remove_newpost_following_user_follower_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="newpost",
            name="like",
            field=models.ManyToManyField(
                related_name="like_post", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
